# Generated by Django 4.0.1 on 2022-02-01 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_created_at_alter_product_updated_at'),
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='products',
            field=models.ManyToManyField(related_name='bill_pruducts', to='products.Product'),
        ),
        migrations.DeleteModel(
            name='BillProduct',
        ),
    ]
