# Generated by Django 4.0.1 on 2022-02-01 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0003_alter_bill_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='products',
        ),
    ]
